import type { Metadata } from "next";
import { IBM_Plex_Mono, Fraunces, Inter } from 'next/font/google';
import "./globals.css";

const fontIbmMono = IBM_Plex_Mono({
 weight: ['200', '300', '400', '500'],
 variable: '--font-mono',
});

const fontFraunces = Fraunces({
  variable: '--font-Fraunces',
  subsets: ["latin"],
});

const fontInter = Inter({
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${fontIbmMono.variable} ${fontFraunces.variable} ${fontInter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
