import type { Metadata } from 'next';
import { IBM_Plex_Mono, Fraunces, Inter } from 'next/font/google';
import { AppProvider } from './provider';
import { getLocale } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';
import './globals.css';

const fontIbmMono = IBM_Plex_Mono({
  weight: ['200', '300', '400', '500'],
  variable: '--font-ibm-mono',
});

const fontFraunces = Fraunces({
  variable: '--font-fraunces',
  subsets: ['latin'],
});

const fontInter = Inter({
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'NextHunt',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: LayoutProps<'/'>) {
  const locale = await getLocale();
  return (
    <html lang={locale} className={`${fontIbmMono.variable} ${fontFraunces.variable} ${fontInter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <NextIntlClientProvider>
          <AppProvider>{children}</AppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
